### ISSUE TITLE
MIddleware - SQL quering

### ISSUE THREAD

**Issue by blake214** [blake214/Agile_project#9]
1. Work on the get and post requests to include sql queries to the database
2. Replace the dummy data with the proper data

**Comment by hadarsharon** [comment]
@blake214 I added code under db/db.js that populates the DB with a new product to be added, chained to the API request and all. Should be very easy to trigger & work with. That brings us to proper data instead of dummy data.

As for pulling the data from the database and templating it in some HTML or something, I haven't done that yet.
